name: zzz test secrets in if

on:
  push:
    branches: [c6-freshness]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "step 1"
      - if: secrets.VERCEL_TOKEN != ''
        run: echo "step 2, should be skipped"
